// Statický slovník značek a modelů pro rozpoznání vozidla ve volném textu,
// nezávisle na tom, jestli vozidlo už v databázi existuje. Klíč je token
// v textu (lowercase, bez diakritiky), hodnota je kanonický název pro zápis.
export const BRAND_KEYWORDS: Record<string, string> = {
  skoda: 'Škoda',
  škoda: 'Škoda',
  bmw: 'BMW',
  vw: 'VW',
  volkswagen: 'VW',
  ford: 'Ford',
  audi: 'Audi',
  hyundai: 'Hyundai',
  kia: 'Kia',
  toyota: 'Toyota',
  renault: 'Renault',
  peugeot: 'Peugeot',
  citroen: 'Citroën',
  citroën: 'Citroën',
  opel: 'Opel',
  seat: 'Seat',
  mercedes: 'Mercedes-Benz',
  fiat: 'Fiat',
  dacia: 'Dacia',
  mazda: 'Mazda',
  honda: 'Honda',
  volvo: 'Volvo',
  suzuki: 'Suzuki',
  mitsubishi: 'Mitsubishi',
};

export const MODEL_KEYWORDS: Record<string, { brand: string; model: string }> = {
  octavia: { brand: 'Škoda', model: 'Octavia' },
  fabia: { brand: 'Škoda', model: 'Fabia' },
  superb: { brand: 'Škoda', model: 'Superb' },
  kodiaq: { brand: 'Škoda', model: 'Kodiaq' },
  karoq: { brand: 'Škoda', model: 'Karoq' },
  passat: { brand: 'VW', model: 'Passat' },
  golf: { brand: 'VW', model: 'Golf' },
  polo: { brand: 'VW', model: 'Polo' },
  tiguan: { brand: 'VW', model: 'Tiguan' },
  transit: { brand: 'Ford', model: 'Transit' },
  focus: { brand: 'Ford', model: 'Focus' },
  fiesta: { brand: 'Ford', model: 'Fiesta' },
  '320d': { brand: 'BMW', model: '320D' },
  '520d': { brand: 'BMW', model: '520D' },
};

// Klíčové slovo -> kanonický název práce/úkonu zapisovaný na zakázku.
// Pořadí položek určuje prioritu při shodě víceslovných frází.
export const TASK_KEYWORDS: Array<{ pattern: RegExp; label: string }> = [
  { pattern: /\bolej\w*\b/i, label: 'Výměna motorového oleje a filtrů' },
  { pattern: /\bbrzd\w*\b/i, label: 'Zkontrolovat brzdy' },
  { pattern: /\brozvod\w*\b/i, label: 'Výměna rozvodů' },
  { pattern: /\bdiagnostik\w*\b/i, label: 'Diagnostika' },
  { pattern: /\bklepani|klepán[íi]|klepe\w*\b/i, label: 'Diagnostika klepání' },
  { pattern: /\bpneu\w*\b/i, label: 'Výměna pneumatik' },
  { pattern: /\bstk\b/i, label: 'STK - příprava vozidla' },
  { pattern: /\bspojk\w*\b/i, label: 'Výměna spojky' },
  { pattern: /\btlumi\w*\b/i, label: 'Kontrola/výměna tlumičů' },
];

export const DAY_KEYWORDS: Record<string, number | 'today' | 'tomorrow'> = {
  dnes: 'today',
  zitra: 'tomorrow',
  zítra: 'tomorrow',
  pondeli: 1,
  pondělí: 1,
  po: 1,
  utery: 2,
  úterý: 2,
  ut: 2,
  út: 2,
  streda: 3,
  středa: 3,
  st: 3,
  ctvrtek: 4,
  čtvrtek: 4,
  ct: 4,
  čt: 4,
  patek: 5,
  pátek: 5,
  pa: 5,
  pá: 5,
  sobota: 6,
  so: 6,
  nedele: 0,
  neděle: 0,
  ne: 0,
};
